
spring:
  cache.type: none
  devtools.restart.enabled: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-18-214-211-47.compute-1.amazonaws.com:5432/dcb0kp6fke1npd
    username: ntrvgbigjgewga
    password: 49fad439b9f9501ee15267a4589444af34ae591e39d7741ba34f377fa1052921
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    generate-ddl: true