spring:
  cache.type: none
  devtools.restart.enabled: true
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-197-254-117.compute-1.amazonaws.com:5432/dc3e2lefurffg0
    username: jmxjsnelhqjoot
    password: 2169927e86b4feaa01d6046fd6fadb07e5cf32d2ccc7ef3756157c93c7729602
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
    generate-ddl: true
    properties:

      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      org.hibernate.envers.audit_table_prefix: AUD_
      org.hibernate.envers.audit_table_suffix: null
  h2.console:
    enabled: true
    path: /db
  messages:
    basename: i18n/messages
    encoding: ISO-8859-1
  servlet.multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  mail:
    host: smtp.gmail.com
    username: cesargymapp@gmail.com
    password: g9X#W91h
    port: 587
    properties: 
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true 
      mail.smtp.starttls.required: true 
      mail.smtp.ssl.enable: false
    test-connection: false
  freemarker:
    template-loader-path: classpath:/templates/emails
    check-template-location: true
app:
  email-from: cesar-gym-app@gmail.com
  app-prefix: cesargymapp://
  reset-password-link: http://localhost:8080/reset-password/
  confirm-email-link: http://localhost:8080/profile/confirm-email/
  firebaseAndroidId: com.cesararaujostudio.app
  firebaseIosId: com.cesararaujostudio.app
  firebaseServerKey: AAAAPbTX6yA:APA91bG-L3q1NBIeKxE_ikx5E_Bdg0yE-uyINpmga9hlFBWlAPjVErSubx4nUQtYMjfUCnbXd2zl9pTDNZzCsvlH6dm-_VE8Y_wERXLE9yB466bxbTyvz6hJdjwV2Js2M6w7M5jWeGaA

